# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 1

  - name: Publications
    identifier: publications
    weight: 2
  - name: Journal Article
    parent: publications
    url: "/publication-type/journal-article/"
    weight: 1
  - name: Conference Paper / Presentation
    parent: publications
    url: "/publication-type/international-conference/"
    weight: 2
  - name: Domestic Conference Paper / Presentation
    parent: publications
    url: "/publication-type/domestic-conference/"
    weight: 3

  - name: Talks
    url: /#talks
    weight: 3
  # - name: News
  #   url: /#news
  #   weight: 13
  - name: Experience
    url: experience
    weight: 4
  # - name: Projects
  #   url: projects/
  #   weight: 30
  # - name: Teaching
  #   url: teaching/
  #   weight: 40
  - name: Awards & Grants
    url: /#awards-and-grants
    weight: 5
